spring:
  application:
    name: HomeService

  datasource:
    url: jdbc:postgresql://localhost:5432/homeServices
    username: postgres
    password: mostafa11684
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          show_sql: true

          server:
            port: 8080


            file:
              valid-extensions: jpg,png,jpeg,pdf,xlsx,xls,doc,docx
              download:
                block-size: 8080
